#include <linux/ioctl.h>


typedef struct _RECEIVE_BUFFER_INFO
{
	u32		receive_buffer_size;
	u32 	receive_buffer_gpadl_handle;
	void*	receive_buffer;
	bool	receive_buffer_tainted;
}
RECEIVE_BUFFER_INFO;

#define HYPERV_IOCTL_MAGCI 0x4B
#define HYPERV_IOCTL_INIT_RECV_BUF_SEND_BUFFER _IOR(HYPERV_IOCTL_MAGCI, 1, u32)
#define HYPERV_IOCTL_INIT_RECV_BUF_ESTABLISH_GPADL _IOWR(HYPERV_IOCTL_MAGCI, 6, RECEIVE_BUFFER_INFO)
#define HYPERV_IOCTL_DESTROY_RECV_BUF _IOR(HYPERV_IOCTL_MAGCI, 7, RECEIVE_BUFFER_INFO)
#define HYPERV_IOCTL_CHECK_RECEIVE_BUFFER_TAINTED _IOWR(HYPERV_IOCTL_MAGCI, 8, RECEIVE_BUFFER_INFO)

#define HYPERV_IOCTL_SEND_RNDIS_PKT_KEEPALIVE _IOR(HYPERV_IOCTL_MAGCI, 2, bool)
#define HYPERV_IOCTL_SEND_RNDIS_PKT_QUERY _IO(HYPERV_IOCTL_MAGCI, 3)
#define HYPERV_IOCTL_SEND_RNDIS_PKT_COMPLETE _IO(HYPERV_IOCTL_MAGCI, 5)
#define HYPERV_IOCTL_BLOCK_RNDIS_PKT_THREAD _IOR(HYPERV_IOCTL_MAGCI, 4, bool)